### ISSUE TITLE
AdministrativeState is non in sync with STATE

### ISSUE THREAD

**Issue by gspe** [craftyguy/networkd-dispatcher#24] opened 2017-06-19 13:57 UTC
I've installed the last version 1.5 and I've found that the AdministrativeState is not in sync with STATE
this is the json file:
```
json:
{"Type": "ether",
"OperationalState": "routable",
"AdministrativeState": "configuring",
"Link File": ["/usr/lib/systemd/network/99-default.link"],
"Network File": ["/etc/systemd/network/20-wired.network"],
"State": ["routable (configured)"],
"Path": ["pci-0000:00:19.0"],
"Driver": ["e1000e"],
"Vendor": ["Intel Corporation"],
"Model": ["82579V Gigabit Network Connection (P8P67 Deluxe Motherboard)"],
"HW Address": ["c8:60:00:e3:5c:4d (ASUSTek COMPUTER INC.)"],
"Address": ["192.168.0.109", "fe80::ca60:ff:fee3:5c4d"],
"Gateway": ["192.168.0.1", "fe80::2c72:1ff:fea7:b982 (TP-LINK TECHNOLOGIES CO.,LTD.)"],
"DNS": ["84.200.69.80", "84.200.70.40"]} 
```
AdministrativeState is:
```
"AdministrativeState": "configuring"
```
but should be 
```
"State": ["routable (configured)"]
```

**Comment by craftyguy** [comment] 2017-06-25 18:01
This seems to be caused by a race condition where the interface is no longer in the same state as it was when this state change trigger went off, i.e. when some interfaces come up they appear to change states very rapidly. I went about resolving this in a hackish way, by using the state retrieved from `networkctl list` command and not from the `networkctl status` command. The former is called to get the state of the interface, and the later is called later on in the program to get more information about the interface. 

Commit db8e7e1 implements this. Please check it out if you can, and if it works for you I'll post a new release.

**Closed** 2017-06-25 18:05 UTC

**Comment by charles-dyfis-net** [comment] 2017-06-27 19:48
This seems like fixing only one symptom of a much larger problem -- if we're missing IP address info (f/e), that means the hooks we run are likely to behave in a manner that's not as-designed on a significantly larger scale.

**Comment by craftyguy** [comment] 2017-06-27 19:55
I was seeing that the state would actually change very rapidly and since 'state' is collected fairly early it was causing admin state to be different than the value of 'state'. Should I ignore the admin state 'configured' when there is no IP set (even though we are literally reporting what systemd tells us)?

This almost seems like two separate issues: 1) state read at different times and reported all at once (via json), creating a race condition, and 2) being triggered by a change in admin state to 'configured' but not actually having an IP assigned yet.

Or were you referring to some other issue?

**Comment by craftyguy** [comment] 2017-06-27 19:59
@charles-dyfis-net it seems like you deleted your comment as I was responding to it. Anyways, I'll take that as either you were commenting on the wrong ticket or you wanted to revise/rewrite it :)

**Comment by gspe** [comment] 2017-06-27 20:39
I've tested last version and now seams that STATE and AdministrativeState now are in sync.

The only problem is that now the AdministrativeState are always "configuring", I don't know if this is a systemd bug that doesn't push a "configured" signal or is netword-dispatcher that doesn't catch it.
But having a "configured" state is what we want to be sure that the interface is proper configured and we can fire the script.
